### ISSUE TITLE
Arcgis js api 4.9, creating FeatureLayer from client-side graphics, error Module not found: esri/layers/graphics/sources/support/MemorySourceWorker

### ISSUE THREAD

**Issue by mihaSoro** [Esri/arcgis-webpack-plugin#26] opened 2018-10-13 15:25 UTC
After the update to arcgis js api 4.9, when I try to create a Feature Layer from client side graphics, I get this error that the module "esri/layers/graphics/sources/support/MemorySourceWorker" is not found.

**Comment by wspresto** [comment] 2018-10-30 18:11
Plaz fix! Our application is transitioning from gulp js -> webpack and this is one of the breaking changes that we need fixed.

**Comment by g3r4n** [comment] 2018-11-01 04:44
importing the missing module into my application fixed it for me.

**Comment by roemhildtg** [comment] 2018-11-01 14:46
I just ran into another similar error today. When using the dojo charting stuff in the popups it throws an error about dojox chart modules missing...@g3r4n 's solution worked for me there too.

**Comment by wspresto** [comment] 2018-11-03 17:47
@g3r4n  Could you please provide a code snippet? Any possible details perhaps?

**Comment by g3r4n** [comment] 2018-11-06 09:06
@wspresto here a sample ( on the  featurelayer-demo branch ) : 
https://github.com/g3r4n/jsapi-webpack/tree/featurelayer-demo
based on the esri sample:
https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=layers-featurelayer-collection

**Comment by odoe** [comment] 2018-11-20 13:59
This will be fixed in the next release.

**Comment by tograh** [comment] 2019-02-04 17:48
Using the jsapi-resources/4.x/webpack/demo, I've tried that workaround, but I still occasionally get a _build_ that will not run and that instead emits the MemorySourceWorker error.   Starting with a base on that sample app, I've added the recommended import in both config.ts and app.tsx, and I've even added an import().then() wrap around the App.tx "onAfterCreate()" code.

I thought the problem was fixed until I did an npm install today on a fresh machine, and it cropped up again (arcgis/webpack-plugin 4.10.2).  Now I'm puzzled.

**Comment by odoe** [comment] 2019-02-27 18:20
Can you try the latest demo app again?
https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo

There have been some updates to some of our underlying dependencies that might have fixed the issue. I'm not able to repro, but if you're at DevSummit next week, feel free to find me in the showcase at the Web island.

**Comment by tograh** [comment] 2019-02-27 22:12
It looks like, apart from the move of the Promise import, there were two changes to the package.json: updating the types and moving the plugin version to 4.10.5.  I'm trying that, and I'll plan to pipe up if I see the build failure again.

**Comment by tograh** [comment] 2019-02-28 21:46
Having updated the @arcgis/webpack-plugin dependency to "~4.10.5", I'm still seeing a build failure (i.e., a successful build that, when run, always errors out with "Module not found: support/MemorySourceWorker") approximately every 10th build, which baffles me.

**Comment by odoe** [comment] 2019-02-28 22:38
Is it the sample app here https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo

Can you provide some more details:

OS:
Node Version:
NPM Version:

Thanks

**Comment by tograh** [comment] 2019-02-28 22:41
It's based on that.  See https://github.com/sassoftware/sas-visualanalytics-geowebmap (the webpack410 branch, specifically).

MacOS
node: 11.1.0
npm: 6.5.0

I emailed you further info separately.

**Comment by odoe** [comment] 2019-05-16 15:12
I'm going to close this one up for now, but if the issue persists, we can look into it further. Tough one to debug.

**Closed by odoe** 2019-05-16 15:12 UTC

**Comment by wspresto** [comment] 2019-05-16 16:19
I just ditched ESRI. Life is better now.

**Comment by tograh** [comment] 2019-05-23 21:32
Previously, in this situation, I was getting fatal MemorySourceWorker errors that rendered ~4% of the builds unusable--in one round of tests, it was 3 failures out of 75 attempts.  After updating to the 4.11 release this week, I ran another round and had 0 of 75 failures.  I can no longer reproduce the problem.

**Comment by tomwayson** [comment] 2019-05-24 14:55
@wspresto if you discover that you need the ArcGIS API for your current or a future app, you might try [esri-loader](https://github.com/Esri/esri-loader) next time.
